### ISSUE TITLE
Player movement with WASD broken

### ISSUE THREAD

**Issue by allisaurus** [o3de/o3de-multiplayersample#220]
**Describe the bug**
Character directional inputs have no effect, character remains in place despite WASD inputs. 
Jumping, shooting, and aiming (w/ mouse) still work. Also, forward walking _animation_ still plays when pressing W.

Also saw these errors in the console, not sure they're relevant but they do refer to the network transform:
```
[Warning] (System) - Processing time exceeded, discarding 9/21 received packets
(EditorServer) - System: ** Autonomous Desync - Corrected clientInputId=1 at hostFrame=6 hostTime=-3
[Warning] (System) - ** Autonomous Desync - Correcting clientInputId=1 from host frame=8
[Error] (System) -     Player.NetworkTransformComponentBase.translation.Element.xValue Server=-1.298177 Client=0.000000
[Error] (System) -     Player.NetworkTransformComponentBase.translation.Element.yValue Server=-10.000000 Client=0.000000
(System) - > sys_scale3DMouseTranslation : 0.200000
```

O3DE commit: `4e0c46be1feb`
MPS commit: `2c84827ff`

**Steps to reproduce**
1. build editor project in profile
2. build server launcher
3. open editor
4. hit ctrl + G
5. try to move the player around the level with WASD keys, observe no movement occurs.

**Expected behavior**
WASD would result in visible player movement

**Actual behavior**
WASD inputs result in no visible player movement

**Found in Branch**
development

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows 10
 - GPU: NVidia RTX 3070
 - Memory: 16GB

**Comment by allisaurus** [comment]
potentially related: https://github.com/o3de/o3de-multiplayersample/pull/218

**Comment by lmbr-pip** [comment]
Should be fixed by https://github.com/o3de/o3de/pull/14484

**Comment by LB-HubertUberman** [comment]
@lmbr-pip @allisaurus The issue still occurs on o3de-multiplayersample: Development (https://github.com/o3de/o3de-multiplayersample/commit/db4a2403af00bdd034de61a96af8b8ff8711fb9e) and o3de: Development (https://github.com/o3de/o3de/commit/1065ca1887cdcf8fcab908234c20407bc3b1efdb). Please note that reopening the issue on our side is impossible due to a lack of permissions in o3de-multiplayersample repository. The issue occurs both in Editor and when launched via GameLauncher as a client. Attaching the video and Server.log file for more details. 
[Server.log](https://github.com/o3de/o3de-multiplayersample/files/10783685/Server.log)

https://user-images.githubusercontent.com/96232062/220088062-f4ad000b-1365-4e65-a83b-dd0a2136b570.mp4

**Comment by LB-HubertUberman** [comment]
We attempted to reproduce the issue on the newest development build and confirmed that it did not occur on o3de-multiplayersample: Development (https://github.com/o3de/o3de-multiplayersample/commit/db4a2403af00bdd034de61a96af8b8ff8711fb9e) and o3de: Development (https://github.com/o3de/o3de/commit/9c57ede2d6c25fb5fd7ede42a30cc9240d9a46da).
